default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgresql://neondb_owner:npg_5hpoUyIaft8K@ep-ancient-art-a222vddh-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require

test:
  <<: *default
  url: postgresql://neondb_owner:npg_5hpoUyIaft8K@ep-ancient-art-a222vddh-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
